alcosi/twinfaces

README.md
src/app/twinclass/[twinClassId]/layout.tsx
src/app/twinclass/[twinClassId]/page.tsx
src/app/twinclass/[twinClassId]/twin-class-context.tsx
src/app/twinclass/[twinClassId]/twin-class-statuses.tsx
src/app/twinclass/[twinClassId]/twin-class-twinflows.tsx
src/app/twinclass/[twinClassId]/twin-status-dialog.tsx
src/app/twinclass/[twinClassId]/twinflow/[twinflowId]/page.tsx
src/app/twinclass/[twinClassId]/twinflow/[twinflowId]/transition/[transitionId]/page.tsx
src/app/twinclass/[twinClassId]/twinflow/[twinflowId]/transition/[transitionId]/twinflow-transition-general.tsx
src/app/twinclass/[twinClassId]/twinflow/[twinflowId]/transition/[transitionId]/twinflow-transition-trigger-dialog.tsx
src/app/twinclass/[twinClassId]/twinflow/[twinflowId]/transition/[transitionId]/twinflow-transition-triggers.tsx
src/app/twinclass/[twinClassId]/twinflow/[twinflowId]/transition/[transitionId]/twinflow-transition-validators.tsx
src/app/twinclass/[twinClassId]/twinflow/[twinflowId]/twinflow-general.tsx
src/app/twinclass/[twinClassId]/twinflow/[twinflowId]/twinflow-transitions.tsx
src/components/class-status-view.tsx
src/components/featurer-input.tsx
src/lib/api/api-groups/twin-class-api.ts
src/lib/api/api-groups/twinflow-api.ts
src/lib/api/api-types.ts
src/lib/api/generated/schema.d.ts
src/lib/utils.ts

add filters on Twinflows table

TWINFACES-41:

---

src/app/twinclass/[twinClassId]/twin-class-context.tsx
src/entities/twinClassLink/index.ts

https://alcosi.atlassian.net/browse/TWINFACES-85

[TWINFACES-85] :bug: fix-ts-erros-on-dev

---

src/app/twin/[twinId]/twin-links.tsx
src/entities/twinClassLink/index.ts
src/lib/api/api-groups/twin-api.ts

https://alcosi.atlassian.net/browse/TWINFACES-61

[TWINFACES-61] Changed the API request for links twin

---

src/app/twinclass/page.tsx
src/components/base/data-table/crud-data-table.tsx
src/components/base/data-table/data-table.tsx
src/entities/permission/api/permission-api.ts
src/entities/permission/api/types.ts
src/entities/permission/components/resource-link/resource-link.tsx
src/entities/permission/components/resource-link/tooltip.tsx
src/entities/permission/libs/helpers.ts
src/entities/twin/components/resource-link/tooltip.tsx
src/entities/twinClass/components/resource-link/resource-link.tsx
src/entities/twinClass/components/resource-link/tooltip.tsx
src/entities/twinClassLink/components/resource-link/tooltip.tsx
src/entities/twinClassStatus/components/resource-link/resource-link.tsx
src/entities/twinClassStatus/components/resource-link/tooltip.tsx
src/entities/user/components/resource-link/resource-link.tsx
src/entities/user/components/resource-link/tooltip.tsx
src/screens/permissions/permissions.tsx
src/shared/libs/helpers.ts
src/shared/libs/index.ts
src/shared/libs/type-checkers.ts
src/widgets/crud-data-table/experimental_crud-data-table.tsx

https://alcosi.atlassian.net/browse/TWINFACES-78

[TWINFACES-78] row-grouping

---

src/app/permission/[permissionId]/page.tsx
src/app/permission/layout.tsx
src/app/twinclass/[twinClassId]/twinflow/[twinflowId]/transition/[transitionId]/twinflow-transition-validator-dialog.tsx
src/app/twinclass/[twinClassId]/twinflow/[twinflowId]/transition/[transitionId]/twinflow-transition-validators.tsx
src/entities/permission/api/hooks/index.ts
src/entities/permission/api/hooks/usePermissionSearchV1.ts
src/entities/permission/api/index.ts
src/entities/permission/api/permission-api.ts
src/entities/permission/api/types.ts
src/entities/permission/libs/constants.ts
src/entities/permission/libs/helpers.ts
src/entities/twinFlow/api/types.ts
src/features/permission/context-provider.tsx
src/features/permission/index.ts
src/screens/permission/index.ts
src/screens/permission/permission.tsx
src/screens/permission/views/general-section.tsx
src/screens/permissions/form-fields.tsx
src/screens/permissions/permissions.tsx
src/shared/api/generated/schema.d.ts

**Links to tasks:**
1. https://alcosi.atlassian.net/browse/TWINFACES-75
2. https://alcosi.atlassian.net/browse/TWINFACES-86

[TWINFACES-75] CRUD permission

---

src/components/base/combobox/combobox.tsx
src/components/base/combobox/multi-combobox/index.ts
src/components/base/combobox/multi-combobox/multi-combobox.tsx
src/entities/twinClass/api/api-service.ts
src/entities/twinClass/libs/hooks/useTwinClassSearchV1.ts
src/features/twinClass/selectField/twin-class-select-field.tsx
src/shared/libs/hooks/index.ts
src/shared/libs/hooks/use-debounce/index.ts
src/shared/libs/hooks/use-debounce/useDebouncedCallback.ts
src/shared/libs/hooks/use-debounce/useDebouncedValue.ts
src/shared/libs/index.ts

Link to tak: https://alcosi.atlassian.net/browse/TWINFACES-77

[TWINFACES-77] Add debounce on combobox search

---

src/app/globals.css
src/components/base/data-table/crud-data-table.tsx
src/widgets/crud-data-table/experimental_crud-data-table.tsx
src/widgets/layout/sidebar-layout/layout.tsx
src/widgets/layout/tabs-layout/layout.tsx

**Task:** https://alcosi.atlassian.net/browse/TWINFACES-105

[TWINFACES-105] tabs-scrolling

---

src/app/layout.tsx
src/components/base/button.tsx
src/entities/permission/components/resource-link/tooltip.tsx
src/entities/twin/components/resource-link/tooltip.tsx
src/entities/twinClass/components/resource-link/tooltip.tsx
src/entities/twinClassLink/components/resource-link/tooltip.tsx
src/entities/twinClassStatus/components/resource-link/tooltip.tsx
src/entities/user/components/resource-link/tooltip.tsx
src/shared/ui/avatar.tsx
src/shared/ui/resource-link/tooltip.tsx

**Task:** https://alcosi.atlassian.net/browse/TWINFACES-101

[TWINFACES-101] add delay to tooltip

---

src/app/globals.css
src/widgets/crud-data-table/dialog/dialog.tsx

TASK: https://alcosi.atlassian.net/browse/TWINFACES-97

[TWINFACES-97] scrolling dialog

---

src/components/base/sidebar.tsx
src/shared/libs/hooks/index.ts
src/shared/libs/hooks/use-local-storage.tsx
src/shared/libs/type-checkers.ts
src/widgets/layout/sidebar-layout/layout.tsx

**Link to task:** https://alcosi.atlassian.net/browse/TWINFACES-98

[TWINFACES- 98] use local storage

---

src/app/page.tsx
src/app/twin/[twinId]/layout.tsx
src/app/twin/[twinId]/page.tsx
src/app/twin/page.tsx
src/app/twinclass/[twinClassId]/page.tsx
src/app/twinclass/[twinClassId]/twin-class-context.tsx
src/app/twinclass/[twinClassId]/twin-class-general.tsx
src/app/twinclass/[twinClassId]/twin-class-statuses.tsx
src/app/twinclass/[twinClassId]/twinField/[twinFieldId]/page.tsx
src/app/twinclass/[twinClassId]/twinStatus/[twinStatusId]/page.tsx
src/app/twinclass/[twinClassId]/twinflow/[twinflowId]/page.tsx
src/app/twinclass/[twinClassId]/twinflow/[twinflowId]/transition/[transitionId]/page.tsx
src/app/twinclass/page.tsx
src/app/twinclass/twin-class-dialog.tsx
src/entities/twinClass/libs/hooks/useFindTwinClassById.ts
src/entities/twinClassStatus/libs/hooks/useClassStatuses.tsx
src/features/breadcrumb/types.ts
src/features/twinClass/selectField/twin-class-select-field.tsx
src/screens/twinClassLink/twinClassLink.tsx

Link to task: https://alcosi.atlassian.net/browse/TWINFACES-93

[TWINFACES-93]-refactor-breadcrumbs

---

src/app/twinclass/[twinClassId]/twin-class-general.tsx

Task: https://alcosi.atlassian.net/browse/TWINFACES-108

[TWINFACES-108] Extends-is-not-shown-on-twin-class-general

---

src/components/base/sidebar.tsx
src/widgets/layout/sidebar-layout/content.tsx
src/widgets/layout/sidebar-layout/header.tsx
src/widgets/layout/sidebar-layout/layout.tsx

**Task:** https://alcosi.atlassian.net/browse/TWINFACES-109

[TWINFACES-109] fix-sidebar-layout

---

src/widgets/crud-data-table/dialog/dialog.tsx

**Task:** https://alcosi.atlassian.net/browse/TWINFACES-103

[TWINFACES-103] fix-dialog-layout

---

.prettierignore
src/app/permission-group/page.tsx
src/components/auto-field.tsx
src/entities/permissionGroup/api/hooks/index.ts
src/entities/permissionGroup/api/hooks/useFetchById.ts
src/entities/permissionGroup/api/hooks/useSearchV1.ts
src/entities/permissionGroup/api/index.ts
src/entities/permissionGroup/api/permission-group-api.ts
src/entities/permissionGroup/api/types.ts
src/entities/permissionGroup/index.ts
src/entities/permissionGroup/libs/helpers.ts
src/entities/permissionGroup/libs/index.ts
src/features/api-context-provider/api-context-provider.tsx
src/features/permissionGroup/index.ts
src/features/permissionGroup/selectField/index.ts
src/features/permissionGroup/selectField/permission-group-select-field.tsx
src/screens/permissionGroups/index.ts
src/screens/permissionGroups/permissionGroups.tsx
src/screens/permissions/form-fields.tsx
src/screens/permissions/permissions.tsx
src/shared/api/generated/schema.d.ts
src/shared/libs/helpers.ts
src/widgets/layout/sidebar-layout/sidebar.tsx

**Task:** https://alcosi.atlassian.net/browse/TWINFACES-95

[TWINFACES-95] implement permission groups

---

components.json
package-lock.json
package.json
src/components/base/radio-group.tsx
src/widgets/crud-data-table/header/group-by-button.tsx

**Task:** https://alcosi.atlassian.net/browse/TWINFACES-112

[TWINFACES-112] checkboxes 2 radioboxes

---

package-lock.json
package.json
src/app/twinclass/[twinClassId]/twinStatus/[twinStatusId]/twin-status-general.tsx
src/components/base/color-picker.tsx
src/entities/twinClassStatus/components/resource-link/resource-link.tsx
src/shared/ui/resource-link/resource-link.tsx

**Task:** https://alcosi.atlassian.net/browse/TWINFACES-120

[TWINFACES-120] redesign-statuses

---

src/entities/permissionGroup/api/permission-group-api.ts

**Task:** https://alcosi.atlassian.net/browse/TWINFACES-210

[TWINFACES-210] permission groups table

---

src/entities/twinClass/components/resource-link/tooltip.tsx

Task: https://alcosi.atlassian.net/browse/TWINFACES-66

TWINFACES-66 [smart link] class

---

src/app/twinclass/[twinClassId]/twinflow/[twinflowId]/transition/[transitionId]/twinflow-transition-general.tsx
src/app/twinclass/[twinClassId]/twinflow/[twinflowId]/twinflow-general.tsx
src/features/inPlaceEdit/in-place-edit.tsx
src/screens/twinFlowTransitions/transitions.tsx

Task: https://alcosi.atlassian.net/browse/TWINFACES-187

[TWINFACES-187] fix table transitions

---

src/app/twin/[twinId]/views/twin-comments.tsx
src/entities/comment/api/api-service.ts
src/entities/comment/api/hooks/index.ts
src/entities/comment/api/hooks/useFetchComments.tsx
src/entities/comment/api/index.ts
src/entities/comment/api/types.ts
src/entities/comment/components/CommentCard.tsx
src/entities/comment/components/index.ts
src/entities/comment/libs/helpers.ts
src/entities/twin/api/api-service.ts
src/features/api-context-provider/api-context-provider.tsx

task: https://alcosi.atlassian.net/browse/TWINFACES-317

[TWINFACES-317] Replaced <CrudDataTable /> with <Experimental_CrudDataTable />

---

src/screens/permissions/permissions.tsx

task: https://alcosi.atlassian.net/browse/TWINFACES-186

[TWINFACES-186] added link group for [table] permisison

---

src/app/twin/[twinId]/page.tsx
src/app/twin/[twinId]/twin-context.tsx
src/app/twin/[twinId]/views/index.ts
src/app/twin/[twinId]/views/twin-history.tsx
src/entities/twin/api/api-service.ts
src/entities/twin/api/hooks/index.ts
src/entities/twin/api/hooks/useFetchHistoryV1.ts
src/entities/twin/api/index.ts
src/entities/twin/api/types.ts

Task: https://alcosi.atlassian.net/browse/TWINFACES-125

[TWINFACES-125] created tab history on the twins page

---

src/app/design-system/page.tsx
src/app/design-system/seeds.ts
src/app/design-system/tabs/input-fields.tsx
src/app/design-system/tabs/resource-links.tsx

[TWINFACES-0] :recycle: Add TableLayout to design-system page

---

src/entities/twinStatus/components/resource-link/resource-link.tsx

Task: https://alcosi.atlassian.net/browse/TWINFACES-67

[TWINFACES-67] smart link status

---

src/app/design-system/components/ui-section.tsx
src/app/design-system/seeds.ts
src/app/design-system/tabs/input-fields.tsx
src/app/design-system/tabs/resource-links.tsx
src/app/twinclass/[twinClassId]/views/twin-class-general.tsx
src/entities/datalist/api/types.ts
src/entities/datalist/components/resource-link/resource-link.tsx
src/entities/datalist/components/resource-link/tooltip.tsx
src/entities/userGroup/api/api-service.ts
src/entities/userGroup/api/hooks/useSearchV1.ts
src/entities/userGroup/api/types/user-group.ts
src/entities/userGroup/libs/helpers.ts
src/entities/userGroup/libs/hooks/index.ts
src/entities/userGroup/libs/hooks/useSelectAdapter.tsx
src/entities/userGroup/libs/index.ts

Tasks:
- https://alcosi.atlassian.net/browse/TWINFACES-154
- https://alcosi.atlassian.net/browse/TWINFACES-261

[TWINFACES-154] input field user group multi

---

src/app/design-system/tabs/input-fields.tsx
src/entities/twinClassLink/libs/hooks/index.ts
src/entities/twinClassLink/libs/hooks/useSelectAdapter.ts
src/entities/twinClassLink/libs/index.ts
src/screens/twinClassLinks/form-fields.tsx

Tasks: 
https://alcosi.atlassian.net/browse/TWINFACES-267
https://alcosi.atlassian.net/browse/TWINFACES-268

TWINFACES-140 input field links

---

src/app/twin/page.tsx
src/entities/twin/api/api-service.ts
src/entities/twin/api/hooks/useSearchV3.ts
src/entities/twin/api/types.ts
src/entities/twin/libs/helpers.ts
src/shared/api/generated/schema.d.ts

task: https://alcosi.atlassian.net/browse/TWINFACES-37

[TWINFACES-37] added Experimental_CrudDataTable for table twins

---

src/widgets/layout/sidebar-layout/sidebar/constants.ts
src/widgets/layout/sidebar-layout/sidebar/group.tsx
src/widgets/layout/sidebar-layout/sidebar/sidebar.tsx

Task: https://alcosi.atlassian.net/browse/TWINFACES-361

TWINFACES-361 UI type menu

---

src/app/users/page.tsx
src/entities/user/api/api-service.ts
src/entities/user/api/hooks/index.ts
src/entities/user/api/hooks/useDomainUserSearchV1.ts
src/entities/user/api/types/domain-user.ts
src/entities/user/api/types/index.ts
src/entities/user/libs/helpers.ts
src/screens/users/index.ts
src/screens/users/users.tsx

Task: https://alcosi.atlassian.net/browse/TWINFACES-38

Twinfaces-38 domain users list

---

src/entities/twinFlowTransition/components/resource-link/resource-link.tsx
src/screens/twinFlowTransitions/transitions.tsx
src/widgets/layout/sidebar-layout/header.tsx
src/widgets/layout/sidebar-layout/sidebar/sidebar.tsx

:bug: Small bug fixes

---

src/app/design-system/tabs/input-fields.tsx
src/entities/twinFlow/api/hooks/useTwinFlowSearchV1.ts
src/entities/twinFlow/libs/hooks/useSelectAdapter.ts

Task:
- https://alcosi.atlassian.net/browse/TWINFACES-259
- https://alcosi.atlassian.net/browse/TWINFACES-266

TWINFACES-259 twinflow schema && TWINFACES-266 twinflow

---

src/entities/domain/api/api-service.ts
src/entities/domain/api/hooks/index.ts
src/entities/domain/api/hooks/useDomains.ts
src/entities/domain/api/index.ts
src/entities/domain/api/types.ts
src/entities/domain/index.ts
src/entities/domain/libs/helpers.ts
src/entities/domain/libs/index.ts
src/features/api-context-provider/api-context-provider.tsx
src/widgets/layout/sidebar-layout/sidebar/sidebar.tsx

Task: https://alcosi.atlassian.net/browse/TWINFACES-148

TWINFACES-34 Fetch domains list

---

src/app/workspace/attachments/page.tsx
src/app/workspace/branches/page.tsx
src/app/workspace/business-accounts/page.tsx
src/app/workspace/erasers/page.tsx
src/app/workspace/factories/page.tsx
src/app/workspace/multiplier-filters/page.tsx
src/app/workspace/multipliers/page.tsx
src/app/workspace/options/page.tsx
src/app/workspace/pipeline-steps/page.tsx
src/app/workspace/pipelines/page.tsx
src/app/workspace/subsets/page.tsx
src/app/workspace/tiers/page.tsx
src/app/workspace/transitions/page.tsx
src/app/workspace/twinflow-schemas/page.tsx
src/app/workspace/twinflows/page.tsx

task: https://alcosi.atlassian.net/browse/TWINFACES-361

[TWINFACES-361] added <UnderConstruction/> to unimplemented pages

---

src/entities/twinClass/api/types.ts
src/entities/twinClass/libs/hooks/useFilters.ts

task: https://alcosi.atlassian.net/browse/TWINFACES-141

[TWINFACES-141] added filter view permission

---

src/entities/twinRole/api/api-service.ts
src/entities/twinRole/api/hooks/index.ts
src/entities/twinRole/api/hooks/useSearchTwinRoles.ts
src/entities/twinRole/api/index.ts
src/entities/twinRole/api/types.ts
src/entities/twinRole/index.ts
src/entities/twinRole/libs/helpers.ts
src/entities/twinRole/libs/index.ts
src/features/api-context-provider/api-context-provider.tsx
src/screens/permission/views/grant-section/grant-section.tsx
src/screens/permission/views/grant-section/twin-role-table.tsx
src/shared/api/generated/schema.d.ts

task: https://alcosi.atlassian.net/browse/TWINFACES-217

[TWINFACES-217] added twin roles table

---

src/entities/assigneePropagation/api/api-service.ts
src/entities/assigneePropagation/api/hooks/index.ts
src/entities/assigneePropagation/api/hooks/useSearchAssigneePropagation.ts
src/entities/assigneePropagation/api/index.ts
src/entities/assigneePropagation/api/types.ts
src/entities/assigneePropagation/index.ts
src/entities/assigneePropagation/libs/helpers.ts
src/entities/assigneePropagation/libs/index.ts
src/entities/twinRole/api/api-service.ts
src/entities/twinRole/api/types.ts
src/entities/twinRole/libs/helpers.ts
src/features/api-context-provider/api-context-provider.tsx
src/screens/permission/views/grant-section/assignee-propagation-table.tsx
src/screens/permission/views/grant-section/grant-section.tsx
src/screens/permission/views/grant-section/twin-role-table.tsx
src/shared/api/generated/schema.d.ts

task: https://alcosi.atlassian.net/browse/TWINFACES-253

[TWINFACES-253] adding by assignee propagation table

---

src/entities/assigneePropagation/api/api-service.ts
src/entities/assigneePropagation/api/hooks/useSearchAssigneePropagation.ts
src/entities/assigneePropagation/libs/helpers.ts
src/entities/spaceRole/api/api-service.ts
src/entities/spaceRole/api/hooks/index.ts
src/entities/spaceRole/api/hooks/useSearchSpaceRole.ts
src/entities/spaceRole/api/index.ts
src/entities/spaceRole/api/types.ts
src/entities/spaceRole/index.ts
src/entities/spaceRole/libs/helpers.ts
src/entities/spaceRole/libs/index.ts
src/entities/twinRole/api/api-service.ts
src/entities/twinRole/api/hooks/useSearchTwinRoles.ts
src/entities/twinRole/libs/helpers.ts
src/features/api-context-provider/api-context-provider.tsx
src/screens/permission/views/grant-section/grant-section.tsx
src/screens/permission/views/grant-section/space-role-table.tsx
src/shared/api/generated/schema.d.ts

task: https://alcosi.atlassian.net/browse/TWINFACES-218

[TWINFACES-218] add space role table

---

src/shared/ui/sidebar.tsx

Twinfaces-0 fix tooltip provider

---

src/app/workspace/factories/page.tsx
src/entities/factory/api/api-service.ts
src/entities/factory/api/index.ts
src/entities/factory/api/types.ts
src/entities/factory/index.ts
src/entities/factory/libs/hooks/index.ts
src/entities/factory/libs/hooks/useFactorySearch.ts
src/entities/factory/libs/hooks/useFilters.ts
src/entities/factory/libs/index.ts
src/features/api-context-provider/api-context-provider.tsx
src/screens/factories/factories.tsx
src/screens/factories/index.ts

Task: https://alcosi.atlassian.net/browse/TWINFACES-287

[TWINFACES-287] factories list

---

src/app/workspace/factories/[factoryId]/page.tsx
src/app/workspace/pipelines/page.tsx
src/entities/factory/api/api-service.ts
src/entities/factory/components/resource-link/resource-link.tsx
src/entities/factory/components/resource-link/tooltip.tsx
src/entities/factory/libs/hooks/index.ts
src/entities/factory/libs/hooks/useFactorySearch.ts
src/entities/factory/libs/hooks/useFactorySelectAdapter.ts
src/entities/factory/libs/hooks/useFetchFactoryById.ts
src/entities/factoryPipeline/api/api-service.ts
src/entities/factoryPipeline/api/index.ts
src/entities/factoryPipeline/api/types.ts
src/entities/factoryPipeline/index.ts
src/entities/factoryPipeline/libs/hooks/index.ts
src/entities/factoryPipeline/libs/hooks/useFactoryPipelineSearch.ts
src/entities/factoryPipeline/libs/hooks/useFilters.ts
src/entities/factoryPipeline/libs/index.ts
src/features/api-context-provider/api-context-provider.tsx
src/screens/factories/factories.tsx
src/screens/factoryPipelines/factoryPipelines.tsx
src/screens/factoryPipelines/index.ts
src/shared/api/generated/schema.d.ts

Tasks:
https://alcosi.atlassian.net/browse/TWINFACES-323
https://alcosi.atlassian.net/browse/TWINFACES-296

[TWINFACES-323] factory pipeline list & factory resource link

---

src/app/workspace/twin/[twinId]/twin-context.tsx
src/app/workspace/twin/[twinId]/views/twin-general.tsx
src/entities/twin/libs/helpers.ts

task: https://alcosi.atlassian.net/browse/TWINFACES-172

[TWINFACES-172] added resource links to twin general

---

.eslintrc.json
src/entities/featurer/libs/constants.ts
src/entities/featurer/libs/types.ts

TWINFACES-0 :rotating_light: Apply import/no-cycle rule

---

src/app/workspace/user-groups/page.tsx
src/entities/userGroup/api/api-service.ts
src/entities/userGroup/api/hooks/index.ts
src/entities/userGroup/api/types/user-group.ts
src/entities/userGroup/libs/hooks/index.ts
src/entities/userGroup/libs/hooks/useFilters.tsx
src/screens/userGroups/index.ts
src/screens/userGroups/userGroups.tsx

task: https://alcosi.atlassian.net/browse/TWINFACES-225

[TWINFACES-225] created a user groups page

---

src/app/workspace/flow-schemas/page.tsx
src/app/workspace/flow-transitions/page.tsx
src/app/workspace/flows/page.tsx
src/app/workspace/twin/[twinId]/views/twin-general.tsx
src/components/auto-field.tsx
src/components/form-fields/combobox/combobox-form-field.tsx
src/entities/user/api/types/domain-user.ts
src/entities/user/libs/hooks/useSelectAdapter.tsx

Task: https://alcosi.atlassian.net/browse/TWINFACES-172

TWINFACES-172 Fix 'Update Assignee' on [page] twin [tab] general

---

src/widgets/tables/twinClassFields/twin-class-fields.tsx

Task: https://alcosi.atlassian.net/browse/TWINFACES-281

[TWINFACES-281] feat: add breadcrumbs to class fields list page

---

src/widgets/tables/twinClassFields/form-fields.tsx
src/widgets/tables/twinClassFields/twin-class-fields.tsx

task: https://alcosi.atlassian.net/browse/TWINFACES-235

[TWINFACES-235] added select twinClass for modal class field create

---

src/app/workspace/twin/[twinId]/twin-context.tsx
src/app/workspace/twin/[twinId]/views/twin-general.tsx
src/entities/twin/libs/helpers.ts

Task: https://alcosi.atlassian.net/browse/TWINFACES-172

[TWINFACES-172] added lazyRelation: false for api request

---

src/screens/permission/views/grant-section/assignee-propagation-table.tsx
src/screens/permission/views/grant-section/grant-section.tsx
src/screens/permission/views/grant-section/space-role-table.tsx
src/screens/permission/views/grant-section/twin-role-table.tsx
src/screens/permission/views/grant-section/user-groups-table.tsx
src/screens/permission/views/grant-section/users-table.tsx

Task: https://alcosi.atlassian.net/browse/TWINFACES-179

TWINFACES-179 [page] permission [tab] grant

---

src/entities/factoryPipeline/api/api-service.ts
src/entities/factoryPipeline/api/hooks/index.ts
src/entities/factoryPipeline/api/hooks/useFactoryPipelineSearch.ts
src/entities/factoryPipeline/api/index.ts
src/entities/factoryPipeline/api/types.ts
src/entities/factoryPipeline/libs/helpers.ts
src/entities/factoryPipeline/libs/hooks/index.ts
src/entities/factoryPipeline/libs/hooks/useFilters.ts
src/entities/factoryPipeline/libs/index.ts
src/entities/permission/api/hooks/usePermissionSearchV1.ts
src/screens/factoryPipelines/factoryPipelines.tsx

task: https://alcosi.atlassian.net/browse/TWINFACES-323
task: https://alcosi.atlassian.net/browse/TWINFACES-307

[TWINFACES-323] factory pipeline list

---

src/app/workspace/twinclass/[twinClassId]/page.tsx
src/screens/twin-class-relations/form-fields.tsx
src/screens/twin-class-relations/index.ts
src/screens/twin-class-relations/twin-class-links.tsx
src/screens/twinClassLinks/index.ts

Task: https://alcosi.atlassian.net/browse/TWINFACES-166

TWINFACES-166 rename tab to 'Relations'

---

src/features/permissionGroup/selectField/permission-group-select-field.tsx
src/features/twinClass/selectField/twin-class-select-field.tsx
src/shared/ui/button.tsx
src/shared/ui/combobox/combobox.tsx
src/shared/ui/combobox/types.ts

https://alcosi.atlassian.net/browse/TWINFACES-76
немного изменено поведение всех disabled кнопок

TWINFACES-76 task completed, behavior of disabled button changed

---

src/entities/featurer/libs/types.ts
src/entities/pipeline-step/api/api-service.ts
src/entities/pipeline-step/api/types.ts
src/entities/pipeline-step/libs/helpers.ts
src/entities/pipeline-step/libs/hooks/use-filters.ts
src/screens/pipeline-steps/pipeline-steps.tsx
src/shared/api/generated/schema.d.ts

Task: https://alcosi.atlassian.net/browse/TWINFACES-325
добавлены фильтры на condition invert and filler featurer

[TWINFACES-325] table filter factory pipeline steps

---

src/entities/twin/api/api-service.ts
src/entities/twin/components/resource-link/resource-link.tsx
src/entities/twin/components/resource-link/tooltip.tsx
src/entities/twin/libs/helpers.ts

Task: https://alcosi.atlassian.net/browse/TWINFACES-128

[TWINFACES-128] feat: update title format view

---

src/entities/comment/api/api-service.ts
src/entities/comment/api/types.ts
src/entities/comment/components/CommentCard.tsx
src/entities/comment/libs/helpers.ts
src/entities/user/components/resource-link/resource-link.tsx
src/shared/ui/resource-link/resource-link.tsx

Task: https://alcosi.atlassian.net/browse/TWINFACES-175
https://alcosi.atlassian.net/browse/TWINFACES-249
https://alcosi.atlassian.net/browse/TWINFACES-247

[TWINFACES-247] card comment

---

src/screens/twins/form-fields.tsx
src/screens/twins/use-twin-form-fields.ts

Task: https://alcosi.atlassian.net/browse/TWINFACES-456

TWINFACES-456 filter out abstractt twin-classes on twin-create

---

src/entities/twin-status/libs/constants.ts
src/widgets/tables/twin-class-statuses/form-fields.tsx
src/widgets/tables/twin-class-statuses/twin-class-statuses.tsx

Tasks: https://alcosi.atlassian.net/browse/TWINFACES-338
https://alcosi.atlassian.net/browse/TWINFACES-236
added disabled for class input then class selected

[TWINFACES-236] [modal] status create

---

src/components/auto-field.tsx
src/entities/user/libs/hooks/useSelectAdapter.tsx
src/widgets/form-fields/twin-field/twin-field-item.tsx

Task: https://alcosi.atlassian.net/browse/TWINFACES-451

TWINFACES-451 Implment 'selectUserV1' field type for twin-field-input

---

src/screens/twins/twins.tsx

Task: https://alcosi.atlassian.net/browse/TWINFACES-37
Change column Name (delete resource link, add only text) & add column with alias type

[TWINFACES-37] feat: change name column and add alias type column

---

src/entities/twinClass/api/api-service.ts
src/entities/twinClass/api/types.ts
src/entities/twinClass/libs/constants.ts
src/entities/twinClass/libs/helpers.ts
src/screens/twinClasses/twin-classes.tsx

Task: https://alcosi.atlassian.net/browse/TWINFACES-148
Add (not default view) missed column:
Create permission,
View permission ,
Edit permission ,
Delete permission.

 [TWINFACES-148] add missed column

---

src/entities/twinClassLink/api/api-service.ts
src/entities/twinClassLink/api/hooks/index.ts
src/entities/twinClassLink/api/hooks/use-search-v1.ts
src/entities/twinClassLink/api/types.ts
src/entities/twinClassLink/libs/helpers.ts
src/entities/twinClassLink/libs/hooks/index.ts
src/entities/twinClassLink/libs/hooks/use-select-adapter.ts
src/entities/twinClassLink/libs/index.ts
src/widgets/form-fields/featurer/featurer-param-input.tsx
src/widgets/form-fields/featurer/hooks/useSelectAdapter.ts

Task: https://alcosi.atlassian.net/browse/TWINFACES-397
Task: https://alcosi.atlassian.net/browse/TWINFACES-398

TWINFACES-397 Support featurer params: UUID_TWINS_LINK_ID & UUID _SET_TWINS_LINK_ID

---

src/app/workspace/twinclass/[twinClassId]/twinStatus/[twinStatusId]/twin-status-general.tsx
src/shared/api/generated/schema.d.ts

Task: https://alcosi.atlassian.net/browse/TWINFACES-169
Implement ability to edit Key field in the table & add Class link

[TWINFACES-169] update page status tab general

---

src/entities/twin/libs/hooks/useFilters.ts

Task: http://alcosi.atlassian.net/browse/TWINFACES-131

TWINFACES-131 :bug: Fixed twins table filters

---

src/app/workspace/twinclass/[twinClassId]/views/twin-class-general.tsx

Task: https://alcosi.atlassian.net/browse/TWINFACES-163
The table has been updated: added edit fields for permission, tag list and markers;
Not implemented: Extends edit field because task is blocked

[TWINFACES-163] update page class tab general

---

src/entities/twinClass/api/types.ts
src/entities/twinClass/libs/hooks/use-filters.ts
src/screens/twinClasses/twin-classes.tsx

Task: https://alcosi.atlassian.net/browse/TWINFACES-141
Implement: filters by create, view, edit, delete permissions and markers, tags list;
Task: https://alcosi.atlassian.net/browse/TWINFACES-148
Implement: add missing column Owner type after checking task TWINFACES-141

[TWINFACES-141] update table filter classes

---

src/entities/twin-status/libs/constants.ts
src/entities/twin/libs/constants.ts
src/shared/libs/constants.ts
src/widgets/tables/twin-class-fields/constants.ts

Task: http://alcosi.atlassian.net/browse/TWINFACES-420

TWINFACES-420 :bug: Fix assignee field

---

src/entities/twin/api/types.ts
src/entities/twin/libs/hooks/useFilters.ts

added Description input field
changed Head input field
deleted Tags and Markers input fields

[TWINFACES-131] changed table filter twins

---

src/components/form-fields/combobox/combobox-form-item.tsx
src/entities/comment/api/api-service.ts
src/entities/comment/components/CommentCard.tsx
src/entities/domain/api/api-service.ts
src/entities/domain/api/hooks/index.ts
src/entities/domain/api/hooks/use-twin-class-owner-type.ts
src/entities/domain/api/types.ts
src/entities/domain/libs/hooks/index.ts
src/entities/domain/libs/hooks/use-twin-class-owner-type-select-adapter.ts
src/entities/domain/libs/index.ts
src/screens/twinClasses/form-fields.tsx
src/shared/api/generated/schema.d.ts
src/shared/libs/helpers.ts

Tasks: https://alcosi.atlassian.net/browse/TWINFACES-233
https://alcosi.atlassian.net/browse/TWINFACES-264
Добавил корректировку компонента комментария (добавил отображение времени создания комментария, и отобразил кнопки с экшенами которые приходят с бэка, но ни одной заполненной нету, можно моковый массив на тест добавить)
https://alcosi.atlassian.net/browse/TWINFACES-247

[TWINFACES-233] update modal class create form

---

src/widgets/form-fields/featurer/featurer-param-input.tsx

Task: http://alcosi.atlassian.net/browse/TWINFACES-273

TWINFACES-273 :bug: fix featurer input field

---

src/entities/twinClassLink/libs/constants.ts
src/screens/twin-class-relations/twin-class-links.tsx

fix validation for forward  & backward  create forms

Twinfaces 191 & 192 fix create validation

---

src/entities/featurer/libs/types.ts
src/widgets/form-fields/featurer/featurer-input.tsx

Task: https://alcosi.atlassian.net/browse/TWINFACES-273

[TWINFACES-273] Default featurer param values

---

src/widgets/tables/twin-class-fields/constants.ts
src/widgets/tables/twin-class-fields/form-fields.tsx

task: https://alcosi.atlassian.net/browse/TWINFACES-235

[TWINFACES-235] added select for input permission

---

src/shared/ui/dialog.tsx
src/widgets/crud-data-table/dialog/dialog.tsx

[TWINFACES-450] fix dialog corner

---

src/entities/twinClass/libs/constants.ts
src/screens/twinClasses/form-fields.tsx
src/screens/twinClasses/twin-classes.tsx

Task: https://alcosi.atlassian.net/browse/TWINFACES-233
Add autoCreatePermission functional from dto

[TWINFACES-233] fix: add autoCreatePermission functional from dto

---

src/shared/ui/dialog.tsx
src/widgets/crud-data-table/dialog/dialog.tsx

[TWINFACES-450] fix native scroll

---

src/entities/twin/api/api-service.ts
src/entities/twinField/libs/helpers.ts
src/widgets/form-fields/twin-field/helpers.tsx
src/widgets/form-fields/twin-field/twin-field-item.tsx

Task: https://alcosi.atlassian.net/browse/TWINFACES-173
update [page] twin [tab] fields, add resourse links preview, and some changes

[TWINFACES-173] feat: update tab

---

src/components/form-fields/combobox/combobox-form-item.tsx
src/entities/datalist-option/libs/constans.ts
src/widgets/tables/datalist-options/datalist-options.tsx

task: https://alcosi.atlassian.net/browse/TWINFACES-427
task: https://alcosi.atlassian.net/browse/TWINFACES-181

[TWINFACES-427] fixed datalist option display logic for a specific datalist

---

src/widgets/tables/twin-class-fields/twin-class-fields.tsx

Task: https://alcosi.atlassian.net/browse/TWINFACES-283
fix: bug with filters by class

[TWINFACES-283] fix: bug with filters by class

---

src/widgets/tables/twin-class-statuses/twin-class-statuses.tsx

Task: https://alcosi.atlassian.net/browse/TWINFACES-339
fix: bug with filters by class

[TWINFACES-339] fix: bug with filters by class

---

src/shared/api/generated/schema.d.ts
src/widgets/tables/twin-class-fields/constants.ts
src/widgets/tables/twin-class-fields/twin-class-fields.tsx

task: https://alcosi.atlassian.net/browse/TWINFACES-235

[TWINFACES-235] fix TWIN_CLASS_FIELD_SCHEMA

---

src/app/workspace/permission-schemas/[schemaId]/layout.tsx
src/app/workspace/permission-schemas/[schemaId]/page.tsx
src/entities/permission-schema/api/api-service.ts
src/entities/permission-schema/api/hooks/index.ts
src/entities/permission-schema/api/hooks/use-fetch-by-id.ts
src/entities/permission-schema/api/types.ts
src/features/permission-schema/context-provider.tsx
src/features/permission-schema/index.ts
src/screens/permission-schema/index.ts
src/screens/permission-schema/permission-schema.tsx
src/screens/permission-schema/views/general.tsx
src/screens/permission-schema/views/index.ts
src/screens/permission-schemas/permission-schemas.tsx

tsak: https://alcosi.atlassian.net/browse/TWINFACES-227

[TWINFACES-227] added permission schema tab general

---

package-lock.json
package.json

Task: http://alcosi.atlassian.net/browse/TWINFACES-468

TWINFACES-468 Upgrade next.js to v14.2.24

---

src/app/workspace/twins/[twinId]/views/twin-fields.tsx
src/screens/twins/form-fields.tsx
src/widgets/form-fields/twin-field/twin-field-item.tsx

Task: https://alcosi.atlassian.net/browse/TWINFACES-440

TWINFACES-440 :bug: small fixes for [twin field] linked twin

---

src/widgets/tables/datalist-options/form-fields.tsx

task: https://alcosi.atlassian.net/browse/TWINFACES-429

[TWINFACES-429] fix logic disabled input datalist

---

src/entities/twin-class/libs/constants.ts
src/screens/twinClasses/form-fields.tsx
src/screens/twinClasses/twin-classes.tsx
src/shared/api/types.ts

Task: https://alcosi.atlassian.net/browse/TWINFACES-233

TWINFACES-233 :bug: Fix form validation at twin-class create modal

---

src/app/workspace/twins/[twinId]/views/twin-fields.tsx
src/entities/twin-class-field/components/resource-link/resource-link.tsx
src/entities/twin/api/api-service.ts
src/entities/twinField/api/hooks/useFetchFields.ts

Task: https://alcosi.atlassian.net/issues/TWINFACES-173?jql=ORDER%20BY%20created%20DESC
Add resource link for fields, and rename column from Key to Fields

[TWINFACES-173] feat: add twin class field resource link for fields

---

src/app/workspace/branches/[factoryBranchId]/layout.tsx
src/app/workspace/branches/[factoryBranchId]/page.tsx
src/app/workspace/branches/page.tsx
src/entities/factory-branch/api/api-service.ts
src/entities/factory-branch/api/hooks/index.ts
src/entities/factory-branch/api/hooks/use-fetch-by-id.ts
src/entities/factory-branch/api/hooks/use-search-v1.ts
src/entities/factory-branch/api/hooks/use-update.ts
src/entities/factory-branch/api/types.ts
src/entities/factory-branch/libs/index.ts
src/features/api-context-provider/api-context-provider.tsx
src/features/factory-branch/context-provider.tsx
src/features/factory-branch/index.ts
src/screens/factory-branch/factory-branch.tsx
src/screens/factory-branch/index.ts
src/screens/factory-branch/views/factory-branch-general.tsx
src/screens/factory-branch/views/index.ts
src/screens/factory-branches/factory-branches.tsx

Tasks:
But the editing functionality only works on local server via patch

[TWINFACES-331] page factory branch tab general

---

.prettierrc
package-lock.json
package.json
src/components/auto-dialog.tsx
src/components/auto-field.tsx
src/components/class-status-view.tsx
src/components/form-fields/checkbox/checkbox-form-field.tsx
src/components/form-fields/checkbox/checkbox-form-item.tsx
src/components/form-fields/color-picker/color-picker-form-field.tsx
src/components/form-fields/color-picker/color-picker-form-item.tsx
src/components/form-fields/combobox/combobox-form-field.tsx
src/components/form-fields/combobox/combobox-form-item.tsx
src/components/form-fields/form-items-common.tsx
src/components/form-fields/tags/tags-form-field.tsx
src/components/form-fields/tags/tags-form-item.tsx
src/components/form-fields/text/text-form-field.tsx
src/components/form-fields/text/text-form-item.tsx
src/components/form-fields/text/textarea-form-field.tsx
src/components/form-fields/text/textarea-form-item.tsx
src/components/theme-provider.tsx
src/components/theme-toggle.tsx

Task: https://alcosi.atlassian.net/browse/TWINFACES-480

TWINFACES-480 Enforce prettier import ordering

---

src/app/workspace/multipliers/page.tsx
src/entities/factory-branch/libs/hooks/use-filters.ts
src/entities/factory-multiplier/api/api-service.ts
src/entities/factory-multiplier/api/hooks/index.ts
src/entities/factory-multiplier/api/hooks/use-search-v1.ts
src/entities/factory-multiplier/api/index.ts
src/entities/factory-multiplier/api/types.ts
src/entities/factory-multiplier/index.ts
src/entities/factory-multiplier/libs/helpers.ts
src/entities/factory-multiplier/libs/hooks/index.ts
src/entities/factory-multiplier/libs/hooks/use-filters.ts
src/entities/factory-multiplier/libs/index.ts
src/entities/featurer/libs/types.ts
src/features/api-context-provider/api-context-provider.tsx
src/screens/factory-multipliers/factory-multipliers.tsx
src/screens/factory-multipliers/index.ts

Tasks: 
🚨 Column Multiplier featurer is missing in DTO and filter by description dont work, waiting BE resolve this bugs

[TWINFACES-310] table factory multipliers

---

src/entities/twin-class/libs/constants.ts
src/shared/libs/constants.ts

Task: https://alcosi.atlassian.net/browse/TWINFACES-233
Update regex for field Key in modal class create

[TWINFACES-233] refactor: update regex for Key in modal class create

---

src/app/workspace/multipliers/[multiplierId]/layout.tsx
src/app/workspace/multipliers/[multiplierId]/page.tsx
src/entities/factory-multiplier/api/api-service.ts
src/entities/factory-multiplier/api/hooks/index.ts
src/entities/factory-multiplier/api/hooks/use-fetch-by-id.ts
src/entities/factory-multiplier/api/hooks/use-update.ts
src/entities/factory-multiplier/api/types.ts
src/features/factory-multiplier/context-provider.tsx
src/features/factory-multiplier/index.ts
src/screens/factory-multiplier/factory-multiplier.tsx
src/screens/factory-multiplier/index.ts
src/screens/factory-multiplier/views/factory-multiplier-general.tsx
src/screens/factory-multiplier/views/index.ts
src/screens/factory-multipliers/factory-multipliers.tsx

Task : https://alcosi.atlassian.net/browse/TWINFACES-333
🚨 Edit functional dont work, waiting BE resolve this bugs, and missing multiplierFeaturer in DTO

[TWINFACES-333] page factory multiplier tab general

---

src/entities/datalist-option/libs/hooks/use-filters.ts
src/entities/factory-pipeline-step/libs/hooks/use-filters.ts
src/entities/permission-schema/components/index.ts
src/entities/twin-class-field/libs/hooks/use-filters.ts
src/entities/twin-status/libs/hooks/use-filters.ts
src/screens/factory-pipeline/factory-pipeline.tsx
src/screens/pipeline-steps/pipeline-steps.tsx
src/shared/api/generated/schema.d.ts
src/shared/libs/helpers.ts
src/widgets/layout/sidebar-layout/sidebar/constants.ts
src/widgets/tables/index.ts
src/widgets/tables/pipeline-steps/index.ts
src/widgets/tables/pipeline-steps/pipeline-steps.tsx

Task: https://alcosi.atlassian.net/browse/TWINFACES-328
https://alcosi.atlassian.net/browse/TWINFACES-291

[TWINFACES-328] page factory pipeline tab steps

---

src/app/design-system/components/ui-section.tsx
src/app/design-system/tabs/tables.tsx
src/widgets/tables/twins/twins.tsx

Task: https://alcosi.atlassian.net/browse/TWINFACES-489

TWINFACES-489 :ambulance: Allow selecting twin-class on design-system

---

src/app/workspace/twins/[twinId]/page.tsx
src/entities/twin-class-field/api/api-service.ts
src/entities/twin-class-field/api/types.ts
src/entities/twin-class-field/libs/hooks/use-filters.ts
src/entities/twin/api/types.ts
src/shared/api/generated/schema.d.ts
src/shared/libs/helpers.ts
src/shared/ui/combobox/hooks/use-combobox.tsx
src/widgets/crud-data-table/crud-data-table.tsx
src/widgets/crud-data-table/header/header.tsx
src/widgets/tables/twin-class-fields/twin-class-fields.tsx
src/widgets/tables/twins/twins.tsx

Task: https://alcosi.atlassian.net/browse/TWINFACES-489

[TWINFACES-489] Refactor <TwinsTable />

---

src/app/workspace/twinclass/[twinClassId]/views/twin-class-general.tsx
src/entities/twin-class/api/api-service.ts
src/entities/twin-class/api/hooks/index.ts
src/entities/twin-class/api/hooks/use-fetch-twin-class-by-id.ts
src/entities/twin-class/api/hooks/use-update-twin-class.ts
src/entities/twin-class/api/types.ts
src/entities/twin-class/contexts/context.tsx

task: https://alcosi.atlassian.net/browse/TWINFACES-163 added hydrate for useFetchTwinClassById

[TWINFACES-163] added hydrateTwinClassFromMap for useFetchTwinClassById

---

src/entities/domain/api/types.ts
src/entities/twin-status/api/types.ts
src/entities/twin-status/libs/hooks/use-filters.ts
src/entities/twin-status/libs/hooks/use-select-adapter.tsx
src/shared/api/generated/schema.d.ts
src/shared/config/types.ts
src/widgets/tables/twin-class-statuses/twin-class-statuses.tsx

task: https://alcosi.atlassian.net/browse/TWINFACES-497 Update TwinStatusFilters to Support New API Version
1. supported changes on the backend, replaced twinClassIdList with twinClassIdMap in the filter for statuses

[TWINFACES-497] replaced twinClassIdList with twinClassIdMap in the filter for statuses

---

src/app/layout.tsx
src/entities/face/api/actions/nb.ts
src/entities/face/api/actions/pg.ts
src/entities/face/api/actions/wt.ts
src/entities/face/libs/helpers.ts
src/features/auth/useAuthUser.tsx
src/screens/login/login.tsx

Task: https://alcosi.atlassian.net/browse/TWINFACES-492

TWINFACES-492 Fix login proccess by storing domainId in cookies

---

src/entities/twin-flow/api/types.ts
src/entities/twin-flow/libs/hooks/useFilters.ts
src/features/twinFlow/context-provider.tsx
src/screens/twinClassTwinFlows/twinClassTwinFlows.tsx

1) Changes from the BE are supported (filter by twinClassIdMap and comments dto);
2) Remove resource link in table Classes in row name

[TWINFACES-0] fix filters twinflow transition

---

src/entities/twin-flow-transition/libs/constants.ts
src/screens/twinFlowTransitions/form-fields.tsx

Fix validation in create twinflow transition modal, fields srcTwinStatus & dstTwinStatus

[TWINFACES-0] fix: validation in create twinflow transition modal, fields srcTwinStatus & dstTwinStatus

---

src/entities/factory/libs/hooks/index.ts
src/entities/factory/libs/hooks/use-factory-select-adapter.ts
src/entities/factory/libs/hooks/use-filters.ts
src/screens/factories/factories.tsx

Task: https://alcosi.atlassian.net/browse/TWINFACES-286
🔔NOTE!!! Filter Created by is not implemented, need API extension. In future the API will expand and the task will move to Has chages status

[TWINFACES-286] feat: update filters

---

src/entities/permission/api/api-service.ts
src/entities/permission/api/hooks/index.ts
src/entities/permission/api/hooks/use-create-permission-grant-assignee-propagation.ts
src/entities/permission/api/types.ts
src/entities/permission/libs/constants.ts
src/screens/permission/views/grant-section/assignee-propagation-table/assignee-propagation-table.tsx
src/screens/permission/views/grant-section/assignee-propagation-table/form-fields.tsx

Task: https://alcosi.atlassian.net/browse/TWINFACES-476
Add modal permission grant assignee propagation create

[TWINFACES-476] feat: implement functional for create assignee propagation permission grant

---

src/entities/factory/api/api-service.ts
src/entities/factory/api/hooks/index.ts
src/entities/factory/api/hooks/use-create.ts
src/entities/factory/api/types.ts
src/entities/factory/libs/index.ts
src/entities/factory/libs/schemas.ts
src/screens/factories/factories.tsx
src/screens/factories/form-fields.tsx
src/screens/permission/views/grant-section/assignee-propagation-table/form-fields.tsx

Task: https://alcosi.atlassian.net/browse/TWINFACES-432
Add modal factory create

[TWINFACES-432] feat: add modal factory create

---

package-lock.json
package.json
src/entities/face/api/actions/tw.ts
src/shared/ui/carousel.tsx
src/shared/ui/index.ts
src/widgets/faces/widgets/views/tw001.tsx
src/widgets/faces/widgets/views/tw002.tsx

Task: https://alcosi.atlassian.net/browse/TWINFACES-502
Implement fetching images for slider from API.
NOTE! 
For testing use this TwinId `f436d4f8-e06a-40af-988b-72895b3a3983`

[TWINFACES-502] feat: implement fetching images for slider from API

---

src/app/core/multiplier-filters/page.tsx
src/entities/factory-multiplier-filter/api/api-service.ts
src/entities/factory-multiplier-filter/api/hooks/index.ts
src/entities/factory-multiplier-filter/api/hooks/use-search-v1.ts
src/entities/factory-multiplier-filter/api/index.ts
src/entities/factory-multiplier-filter/api/types.ts
src/entities/factory-multiplier-filter/index.ts
src/entities/factory-multiplier-filter/libs/helpers.ts
src/entities/factory-multiplier-filter/libs/hooks/index.ts
src/entities/factory-multiplier-filter/libs/hooks/use-filters.ts
src/entities/factory-multiplier-filter/libs/index.ts
src/entities/factory-multiplier/components/index.ts
src/entities/factory-multiplier/components/resource-link/index.ts
src/entities/factory-multiplier/components/resource-link/resource-link.tsx
src/entities/factory-multiplier/components/resource-link/tooltip.tsx
src/entities/factory-multiplier/libs/hooks/index.ts
src/entities/factory-multiplier/libs/hooks/use-select-adapter.ts
src/entities/link/api/hooks/use-search-v1.ts
src/features/api/context/private-context-provider.tsx
src/screens/factory-multiplier-filters/factory-multiplier-filters.tsx
src/screens/factory-multiplier-filters/index.ts
src/shared/api/generated/schema.d.ts

Tasks: 
Add factory multiplier filter table, table filters, multiplier resouce link, and multiplier adapter

[TWINFACES-334] [table] factory multiplier filters

---

src/widgets/faces/components/widget-layout-renderer.tsx

Task: https://alcosi.atlassian.net/browse/TWINFACES-507
Fix layout overflow on horizontal scroll in CRUD table

[TWINFACES-507] Fix CrudDataTableHeader layout overflow on horizontal scroll

---

src/entities/twinField/api/hooks/useFetchFields.ts
src/entities/twinField/libs/helpers.ts

task: https://alcosi.atlassian.net/browse/TWINFACES-510

[TWINFACES-510] fix bag for twinField.descriptor.fieldType was undefined

---

src/screens/twin/views/twin-fields.tsx
src/widgets/crud-data-table/crud-data-table.tsx
src/widgets/crud-data-table/data-table/data-table.tsx
src/widgets/crud-data-table/data-table/types.ts

task: https://alcosi.atlassian.net/browse/TWINFACES-511 fix bug editing fields page twin tab fields

[TWINFACES-511] fix bug editing fields page twin tab fields

---

src/components/theme-toggle.tsx

Task: https://alcosi.atlassian.net/browse/TWINFACES-509
Change theme option selection from text to icons

[TWINFACES-509] refactor: change theme option selection from text to icons

---

scripts/create_entity.sh
src/entities/comment/components/resource-link/tooltip.tsx
src/entities/comment/libs/constants.ts
src/entities/comment/libs/index.ts
src/entities/featurer/components/resource-link/tooltip.tsx
src/entities/featurer/libs/constants.ts
src/entities/twin-class-field/components/resource-link/tooltip.tsx
src/entities/twin-class-field/libs/constants.ts
src/entities/twin-class-field/libs/index.ts
src/entities/twin-flow-transition/components/resource-link/tooltip.tsx
src/entities/twin-flow-transition/libs/constants.ts
src/entities/twin-flow/components/resource-link/tooltip.tsx
src/entities/twin-flow/libs/constants.ts
src/entities/twin-flow/libs/index.ts
src/entities/twin-status/components/resource-link/tooltip.tsx
src/entities/twin-status/libs/constants.ts
src/entities/twinFlowSchema/components/resource-link/tooltip.tsx
src/entities/twinFlowSchema/libs/constants.ts
src/entities/twinFlowSchema/libs/index.ts
src/entities/user-group/components/resource-link/tooltip.tsx
src/entities/user-group/libs/constants.ts
src/entities/user-group/libs/index.ts
src/shared/ui/resource-link/constans.ts
src/shared/ui/resource-link/resource-link.tsx
src/shared/ui/resource-link/tooltip.tsx

task: https://alcosi.atlassian.net/browse/TWINFACES-110 
1. added tooltip colors for dark and light theme
2. added logic so that tooltips change depending on the theme
3. removed unused code for this task

[TWINFACES-110] applied a single background color to the tooltip

---

src/components/form-fields/combobox/combobox-form-item.tsx
src/components/form-fields/text/text-form-item.tsx
src/entities/face/api/actions/tw.ts
src/features/inPlaceEdit/in-place-edit.tsx
src/features/twin/ui/constants.ts
src/features/twin/ui/field-editor.tsx
src/features/twin/ui/index.ts
src/screens/twin/views/twin-general.tsx
src/shared/libs/types/checkers.ts
src/shared/ui/icons/index.ts
src/shared/ui/icons/no-image.tsx
src/shared/ui/sliders/slot-slider/components/slot-slider-item.tsx
src/shared/ui/sliders/slot-slider/components/slot-slider-placeholder.tsx
src/shared/ui/sliders/slot-slider/components/slot-slider-thumbnail.tsx
src/shared/ui/sliders/slot-slider/index.ts
src/shared/ui/sliders/slot-slider/slot-slider.tsx
src/shared/ui/sliders/slot-slider/types.ts
src/shared/ui/table.tsx
src/widgets/faces/widgets/views/tw004.tsx
src/widgets/form-fields/twin-field/helpers.tsx

Task: https://alcosi.atlassian.net/browse/TWINFACES-508

TWINFACES-508 Improve <TW004 />

---

src/shared/ui/resource-link/tooltip.tsx

[TWINFACES-110] fix color text tooltip

---

src/entities/face/api/actions/tw.ts
src/entities/face/api/types.ts
src/entities/twin-flow-transition/api/types.ts
src/features/twin-flow-transition/transition-perform-button.tsx
src/features/twin/ui/view-as-admin.tsx
src/shared/api/generated/schema.d.ts
src/widgets/faces/components/widget-layout-renderer.tsx
src/widgets/faces/widgets/renderer.tsx
src/widgets/faces/widgets/views/index.ts
src/widgets/faces/widgets/views/tw005.tsx

task: https://alcosi.atlassian.net/browse/TWINFACES-520 [face twiget] TW005

[TWINFACES-520] added TW005

---

src/entities/twin-flow-transition/libs/constants.ts
src/entities/twin-flow-transition/libs/hooks/use-alias-select-adapter.ts
src/screens/twin/views/twin-fields.tsx
src/shared/libs/constants.ts
src/widgets/tables/twin-flow-transitions/form-fields.tsx

Task: https://alcosi.atlassian.net/browse/TWINFACES-269
Add functional for creating a new alias in Transitions modal create.
Fix bug with view input fields data in edit mode (table Twin tab fields)

[TWINFACES-269] update input field transition alias single

---

src/entities/user/api/actions.ts

Fix error with businessAccountId in login form

[TWINFACES-0] fix: error with businessAccountId in login form

---

src/entities/twin/api/hooks/use-fetch-by-id-v2.ts
src/shared/libs/utils/client-cookies.ts

Fix incorrect authToken format

[TWINFACES-0] fix: incorrect authToken format

---

src/entities/twin-class/libs/helpers.ts

Fix view fields in modal twin create

[TWINFACES-0] fix: view fields in modal twin create

---

src/app/core/twinclass/[twinClassId]/twinField/[twinFieldId]/twin-field-general.tsx

Fix update field typer in twinCalss Fields tab general

[TWINFACES-0] fix-update-field-typer-in-twinCalss-Fields-tab-general

---

src/features/ui/theme-provider.tsx

Task: https://alcosi.atlassian.net/browse/TWINFACES-530
Fix Hydration Errors in login page by toggle theme
Hydration error behavior, on the login page we select a theme other than the system, then reload the page

[TWINFACES-530] Fix Hydration Errors and SVG Mismatch in LoginForm

---

src/entities/domain/api/hooks/use-domains.ts
src/entities/domain/api/types.ts
src/entities/domain/libs/constans.ts
src/features/domain/create-domain-button/create-domain-form.tsx
src/shared/api/generated/schema.d.ts

1. supported new logic for getting domains data

[TWINFACES-0] fix domain schema

---

src/widgets/layout/sidebar-layout/sidebar/menu/menu-item.tsx

Task: https://alcosi.atlassian.net/browse/TWINFACES-503?focusedCommentId=33992
Fix hydration error in button [face navbar] NB001

[TWINFACES-503] fix: hydration error in button [face navbar] NB001

---

package-lock.json
package.json
src/app/core/twinclass/[twinClassId]/views/twin-class-general.tsx
src/app/design-system/page.tsx
src/app/design-system/tabs/action-dialogs.tsx
src/app/design-system/tabs/input-fields.tsx
src/features/ui/action-dialogs/confirm-dialog.tsx
src/features/ui/action-dialogs/context.tsx
src/features/ui/action-dialogs/index.ts
src/features/ui/action-dialogs/use-action-dialogs.ts
src/shared/libs/utils/index.ts
src/shared/libs/utils/string.ts
src/shared/libs/utils/uuid.ts
src/shared/ui/switch.tsx
src/widgets/layout/providers/private.tsx
src/widgets/layout/providers/public.tsx

Task: https://alcosi.atlassian.net/browse/TWINFACES-483

[TWINFACES-483] Switch component, confirm dialogs

---

src/app/layout.tsx
src/screens/login/auth-form.tsx
src/screens/login/form.tsx
src/screens/login/login.tsx
src/shared/ui/index.ts
src/shared/ui/theme-image.tsx

Task: https://alcosi.atlassian.net/browse/TWINFACES-544

TWINFACES-544 :recycle: Refactor <AuthForm />

---

src/features/datalist/ui/resource-link/tooltip.tsx
src/widgets/tables/datalist-options/datalist-options.tsx

task: https://alcosi.atlassian.net/browse/TWINFACES-199 [smart link] datalist: desciption and key data missed in tooltip
1. added `description` and `key` in `tooltip datalist`
2. fixed filter for `dataListIdList`
`test data for filter and tooltip:` /core/datalist-options

[TWINFACES-199] added description and key in tooltip datalist

---

src/features/inPlaceEdit/in-place-edit.tsx
src/features/twin-flow-transition/transition-perform-button.tsx
src/features/twin/ui/field-editor/field-editor.tsx
src/shared/ui/button.tsx
src/widgets/faces/widgets/views/tw005.tsx
src/widgets/faces/widgets/views/tw005/index.ts
src/widgets/faces/widgets/views/tw005/tw005-buttons.tsx
src/widgets/faces/widgets/views/tw005/tw005.tsx

task: https://alcosi.atlassian.net/browse/TWINFACES-520 [face twiget] TW005
1. added an icon to the button
2. for the button chose the Outline
3. move content TW005 (buttons) in line with content TW004
`update!!!` 4. aligned the fields on the general page, removed the indents
test data: `NEXT_PUBLIC_TWINS_API_URL = https://dev-twins-onshelves.esas.by` 
`/workspace/products/e640034a-8e8e-4fd6-b0c8-de03d5ef7950#onshelves`

[TWINFACES-520] added icon in button tw005

---

src/shared/ui/popover.tsx
src/widgets/crud-data-table/header/column-manger-popover.tsx
src/widgets/crud-data-table/header/filters-popover.tsx

task: https://alcosi.atlassian.net/browse/TWINFACES-551 added scroll in ColumnManagerPopover

[TWINFACES-551] added scroll in ColumnManagerPopover

---

src/widgets/faces/widgets/views/wt001/wt001-client.tsx
src/widgets/faces/widgets/views/wt001/wt001.tsx
src/widgets/tables/twins/twins.tsx

Task: https://alcosi.atlassian.net/browse/TWINFACES-549
Add optional “Create” button

[TWINFACES-549] feat: add conditional functional for create twin button

---

src/entities/twin/api/api-service.ts
src/entities/twin/server/api/api-service.ts
src/entities/twin/server/api/types.ts
src/entities/twin/server/libs/helpers.ts
src/widgets/form-fields/twin-field/helpers.tsx
src/widgets/tables/twins/twins.tsx

Task: https://alcosi.atlassian.net/browse/TWINFACES-548
Display resource links in dynamic columns instead of displaying ID

[TWINFACES-548] Improve rendering of dynamic fields (e.g., lists, statuses)

---

src/app/core/twinclass/[twinClassId]/twinflow/[twinflowId]/twinflow-general.tsx

Fixed bug when changing initial status in twinflow

[TWINFACES-0] fix: error in update initial status

---

src/entities/face/api/actions/pg.ts
src/shared/api/generated/schema.d.ts
src/widgets/faces/layouts/views/pg001.tsx
src/widgets/faces/layouts/views/pg002.tsx

Task: https://alcosi.atlassian.net/browse/TWINFACES-560
Added twinId parametr support in PG001, PG002 and refactor fetch PG functions

[TWINFACES-560] [face] PG002 - LayoutFace with Tabbed Views

---

src/features/twin-flow-transition/transition-performer.tsx
src/features/twin-status/ui/resource-link/resource-link.tsx
src/features/twin/ui/field-editor/constants.tsx
src/features/twin/ui/twin-status-actions.tsx
src/screens/twin/views/twin-fields.tsx
src/shared/ui/resource-link/resource-link.tsx
src/styles/tailwind-config.css
src/widgets/faces/widgets/views/wt001/wt001-client.tsx
src/widgets/form-fields/twin-field/helpers.tsx
src/widgets/tables/twins/twins.tsx

Task: https://alcosi.atlassian.net/browse/TWINFACES-57?focusedCommentId=34878
Add disabled for resource links in workspace area

[TWINFACES-57] UI type smart link

---

src/features/permission-group/ui/resource-link/resource-link.tsx

Task: https://alcosi.atlassian.net/browse/TWINFACES-205
Fix typo in URL permission group resource link

[TWINFACES-205] [smart link] permission group

---

src/entities/twin/libs/constants.ts
src/entities/twin/libs/hooks/use-filters.ts
src/shared/libs/types/filters.ts
src/widgets/tables/twins/twins.tsx

In filters fixed:
1) Date filters sent two filters at once End date and Start date;
2) All filters were displayed in the selfFilters, even those that did not conside in enabledColumns

[TWINFACES-0] fix: filters in WT001

---

src/entities/factory/libs/hooks/use-filters.ts

task: https://alcosi.atlassian.net/browse/TWINFACES-286
- added `filter` by `key`

[TWINFACES-286] added filter for key

---

src/entities/face/api/types.ts
src/widgets/faces/widgets/views/tw005/tw005-buttons.tsx
src/widgets/faces/widgets/views/tw005/tw005.tsx

task: https://alcosi.atlassian.net/browse/TWINFACES-520
- Added functionality to disable` tw-005 buttons` and to control visibility via `show_when_inactive.`
workspace/tasks/1ca10658-89cb-490c-980a-3056a116e9d3

[TWINFACES-520] added logic disabled for tw-005 buttons, show_when_inactive

---

src/widgets/tables/twins/twins.tsx

task: https://alcosi.atlassian.net/browse/TWINFACES-524 added logic dynamic label

[TWINFACES-524] added logic for label basic fields

---

.env
src/widgets/auth/forms/email-password-sign-in.tsx
src/widgets/auth/forms/email-password-sign-up.tsx

https://alcosi.atlassian.net/browse/TWINFACES-574

TWINFACES-574 refactor: on failed login or signup keep form fields filled (clear password field for signin form on failed)

---

src/features/ui/masonry.tsx
src/shared/ui/masonry.tsx

https://alcosi.atlassian.net/browse/SHLVS-418

[SHLVS-418] incorrect widget order on amazon product card after fetching from amazon pl

---

src/shared/ui/masked-value.tsx

[TWINFACES-0] fix bag length refresh token

---

src/screens/profile/profile.tsx
src/shared/ui/masked-value.tsx

- :bug: Fix  /profile screen content
- :bug: Fix secret form field's width

:ambulance: Fixes needed for Demo

---

src/entities/twin/libs/schemas.ts
src/entities/twin/server/api/types.ts
src/features/ui/masonry.tsx
src/shared/ui/masonry.tsx
src/widgets/tables/twins/form-fields.tsx

https://alcosi.atlassian.net/browse/TWINFACES-580

TWINFACES-580 refactor: filter twins form fields

---

src/shared/ui/table.tsx

https://alcosi.atlassian.net/browse/TWINFACES-594
Before fix:
After fix:

[TWINFACES-594] fix warning: in html div cannot be a child of tr

---

package-lock.json
src/entities/face/api/actions/widget-twidget.ts
src/entities/face/api/types.ts
src/shared/api/generated/schema.d.ts
src/shared/ui/forms/combobox/selected-options.tsx
src/widgets/crud-data-table/crud-data-table.tsx
src/widgets/crud-data-table/dialog/dialog.tsx
src/widgets/faces/widgets/views/tc/fetch-modal-create-data.ts
src/widgets/faces/widgets/views/tc/index.ts
src/widgets/faces/widgets/views/tc/tc-form.tsx
src/widgets/faces/widgets/views/tw001.tsx
src/widgets/faces/widgets/views/tw004/tw004.tsx
src/widgets/faces/widgets/views/tw005/tw005.tsx
src/widgets/faces/widgets/views/wt001/wt001-client.tsx
src/widgets/faces/widgets/views/wt001/wt001.tsx
src/widgets/faces/widgets/views/wt003/wt003.tsx
src/widgets/tables/twins/twins.tsx

Tasks: 
Implement dynamic TC form

[SHLVS-410] UI. Incorrect field names and required field indicators when creating a marketplace connector

---

src/entities/domain/api/actions.ts
src/widgets/layout/sidebar-layout/layout.tsx
src/widgets/layout/sidebar-layout/sidebar/sidebar.tsx

Task: https://alcosi.atlassian.net/browse/TWINFACES-543

[TWINFACES-543] Refactor Domains Fetching to SSR

---

package-lock.json
package.json

Task: https://alcosi.atlassian.net/browse/TWINFACES-604

TWINFACES-604 :arrow_up: Upgrade next.js to v14.2.30 to fix vulnerabilities

---

src/entities/twin/libs/schemas.ts
src/entities/twin/server/api/types.ts

[TWINFACES-0] fix: twin create modal

---

next.config.mjs
package-lock.json
package.json
src/app/layout.tsx
src/middleware.ts
src/shared/api/client/client.ts

Task: https://alcosi.atlassian.net/browse/SHLVS-667

[SHLVS-667] fix: back next-runtime-env module

---

src/entities/twin-flow-transition/libs/constants.ts
src/features/twin-flow/ui/resource-link/resource-link.tsx
src/widgets/tables/twin-flow-transitions/form-fields.tsx
src/widgets/tables/twin-flow-transitions/twin-flow-transitions.tsx

task: https://alcosi.atlassian.net/browse/TWINFACES-611 bug when creating transition
test: 
- `core/transitions` 
- `core/twinflows/30fbaaac-108e-4638-9877-16bcf96d3ca7#transitions`

[TWINFACES-611] fix bug create transition

---

src/features/inPlaceEdit/in-place-edit.tsx
src/features/twin/ui/field-editor/inherited-field-preview.tsx
src/shared/ui/forms/combobox/combobox.tsx

This reverts commit 8864be0309e4b5b0e978990157af71c066814108.

Revert "SHLVS-666 :bug: Fix text overflowing in <TwinFieldEditor /> (#415)

---

src/widgets/tables/twin-flows/twin-flows.tsx

task: https://alcosi.atlassian.net/browse/TWINFACES-608 fixed filter by current class in twinFlow table
test: `dev-twins-onshelves`
- `core/twinclass/218fae7d-f5ee-3d0c-b2dd-cfc5da1790eb#twinflows`
-  `core/twinflows`

[TWINFACES-608] fixed filter by current class in twinFlow table

---

src/entities/twin-class/api/api-service.ts

https://alcosi.atlassian.net/browse/TWINFACES-258

TWINFACES-258 [input field] class (single)

---

src/entities/twin/libs/hooks/use-twin-form-fields.ts

Fix render selected twin class fields in twin create form

[TWINFACES-0] fix: render selected twin class fields in twin create form

---

src/widgets/auth/forms/email-password-sign-in.tsx

[ONSHELVES-0] added await for setAuthUser
